language: node_js

node_js:
  - "10.6.0"

script:
  - echo "Deploy"

install:
  - npm install -g firebase-tools

after_success:
  - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
  - firebase deploy --token $FIREBASE_TOKEN
